// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitaryCollectiblesBackend.Data;

#nullable disable

namespace MilitaryCollectiblesBackend.Migrations
{
    [DbContext(typeof(MilitaryCollectiblesDbContext))]
    [Migration("20251112215310_InitialCreateAndAlteringSchema")]
    partial class InitialCreateAndAlteringSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtifactTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EraId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OriginId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageArea")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactTypeId");

                    b.HasIndex("EraId");

                    b.HasIndex("OriginId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StorageArea");

                    b.ToTable("Artifacts", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.ArtifactSeries", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SeriesId");

                    b.ToTable("ArtifactSeries", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.ArtifactType", b =>
                {
                    b.Property<int>("ArtifactTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtifactTypeId"));

                    b.Property<string>("ArtifactTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtifactTypeId");

                    b.ToTable("ArtifactTypes", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.BindingType", b =>
                {
                    b.Property<int>("BindingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BindingTypeId"));

                    b.Property<string>("BindingTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BindingTypeId");

                    b.ToTable("BindingTypes", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.CaliberSpec", b =>
                {
                    b.Property<int>("CaliberSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaliberSpecId"));

                    b.Property<string>("CaliberSpecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CaliberSpecId");

                    b.ToTable("CaliberSpecs", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("EraId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OriginId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("StorageArea")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("EraId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OriginId");

                    b.HasIndex("StorageArea");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentTypeId"));

                    b.Property<string>("EquipmentTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentTypes", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Era", b =>
                {
                    b.Property<int>("EraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EraId"));

                    b.Property<string>("EraName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EraId");

                    b.ToTable("Eras", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Insignia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EraId")
                        .HasColumnType("int");

                    b.Property<int>("InsigniaTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OriginId")
                        .HasColumnType("int");

                    b.Property<bool>("PartOfSet")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageArea")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.HasIndex("InsigniaTypeId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OriginId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StorageArea");

                    b.ToTable("Insignias", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.InsigniaSeries", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SeriesId");

                    b.ToTable("InsigniaSeries", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.InsigniaType", b =>
                {
                    b.Property<int>("InsigniaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsigniaTypeId"));

                    b.Property<string>("InsigniaTypeName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("InsigniaTypeId");

                    b.ToTable("InsigniaTypes", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Literature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("BindingTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LiteratureTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageArea")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BindingTypeId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.HasIndex("LiteratureTypeId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StorageArea");

                    b.ToTable("Literatures", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.LiteratureSeries", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SeriesId");

                    b.ToTable("LiteratureSeries", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.LiteratureType", b =>
                {
                    b.Property<int>("LiteratureTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiteratureTypeId"));

                    b.Property<string>("LiteratureTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LiteratureTypeId");

                    b.ToTable("LiteratureTypes", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.MechanicalEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int?>("CaliberSpecId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EraId")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicalEquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OriginId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StorageArea")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaliberSpecId");

                    b.HasIndex("EraId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MechanicalEquipmentTypeId");

                    b.HasIndex("OriginId");

                    b.HasIndex("StorageArea");

                    b.ToTable("MechanicalEquipment", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.MechanicalEquipmentType", b =>
                {
                    b.Property<int>("MechanicalEquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicalEquipmentTypeId"));

                    b.Property<string>("MechanicalEquipmentTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MechanicalEquipmentTypeId");

                    b.ToTable("MechanicalEquipmentTypes", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Origin", b =>
                {
                    b.Property<int>("OriginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OriginId"));

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OriginId");

                    b.ToTable("Origins", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StorageAreaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StorageAreaNotes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StorageArea", (string)null);
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Artifact", b =>
                {
                    b.HasOne("MilitaryCollectiblesBackend.Models.ArtifactType", "ArtifactType")
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtifactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilitaryCollectiblesBackend.Models.Era", "Era")
                        .WithMany("Artifacts")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Origin", "Origin")
                        .WithMany("Artifacts")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.ArtifactSeries", "ArtifactSeries")
                        .WithMany("Artifacts")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.StorageArea", "StorageAreaDetails")
                        .WithMany("Artifacts")
                        .HasForeignKey("StorageArea")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ArtifactSeries");

                    b.Navigation("ArtifactType");

                    b.Navigation("Era");

                    b.Navigation("Origin");

                    b.Navigation("StorageAreaDetails");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Equipment", b =>
                {
                    b.HasOne("MilitaryCollectiblesBackend.Models.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilitaryCollectiblesBackend.Models.Era", "Era")
                        .WithMany("Equipments")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Material", "Material")
                        .WithMany("Equipments")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Origin", "Origin")
                        .WithMany("Equipments")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.StorageArea", "StorageAreaDetails")
                        .WithMany("Equipments")
                        .HasForeignKey("StorageArea")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentType");

                    b.Navigation("Era");

                    b.Navigation("Material");

                    b.Navigation("Origin");

                    b.Navigation("StorageAreaDetails");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Insignia", b =>
                {
                    b.HasOne("MilitaryCollectiblesBackend.Models.Era", "Era")
                        .WithMany("Insignias")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.InsigniaType", "InsigniaType")
                        .WithMany("Insignias")
                        .HasForeignKey("InsigniaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilitaryCollectiblesBackend.Models.Material", "Material")
                        .WithMany("Insignias")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Origin", "Origin")
                        .WithMany("Insignias")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.InsigniaSeries", "InsigniaSeries")
                        .WithMany("Insignias")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.StorageArea", "StorageAreaDetails")
                        .WithMany("Insignias")
                        .HasForeignKey("StorageArea")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Era");

                    b.Navigation("InsigniaSeries");

                    b.Navigation("InsigniaType");

                    b.Navigation("Material");

                    b.Navigation("Origin");

                    b.Navigation("StorageAreaDetails");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Literature", b =>
                {
                    b.HasOne("MilitaryCollectiblesBackend.Models.Author", "Author")
                        .WithMany("Literatures")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.BindingType", "BindingType")
                        .WithMany("Literatures")
                        .HasForeignKey("BindingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilitaryCollectiblesBackend.Models.LiteratureType", "LiteratureType")
                        .WithMany("Literatures")
                        .HasForeignKey("LiteratureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilitaryCollectiblesBackend.Models.Publisher", "Publisher")
                        .WithMany("Literatures")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.LiteratureSeries", "LiteratureSeries")
                        .WithMany("Literatures")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.StorageArea", "StorageAreaDetails")
                        .WithMany("Literatures")
                        .HasForeignKey("StorageArea")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");

                    b.Navigation("BindingType");

                    b.Navigation("LiteratureSeries");

                    b.Navigation("LiteratureType");

                    b.Navigation("Publisher");

                    b.Navigation("StorageAreaDetails");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.MechanicalEquipment", b =>
                {
                    b.HasOne("MilitaryCollectiblesBackend.Models.CaliberSpec", "CaliberSpec")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("CaliberSpecId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Era", "Era")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Manufacturer", "Manufacturer")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.Material", "Material")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.MechanicalEquipmentType", "MechanicalEquipmentType")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("MechanicalEquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilitaryCollectiblesBackend.Models.Origin", "Origin")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilitaryCollectiblesBackend.Models.StorageArea", "StorageAreaDetails")
                        .WithMany("MechanicalEquipments")
                        .HasForeignKey("StorageArea")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CaliberSpec");

                    b.Navigation("Era");

                    b.Navigation("Manufacturer");

                    b.Navigation("Material");

                    b.Navigation("MechanicalEquipmentType");

                    b.Navigation("Origin");

                    b.Navigation("StorageAreaDetails");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.ArtifactSeries", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.ArtifactType", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Author", b =>
                {
                    b.Navigation("Literatures");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.BindingType", b =>
                {
                    b.Navigation("Literatures");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.CaliberSpec", b =>
                {
                    b.Navigation("MechanicalEquipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.EquipmentType", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Era", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Equipments");

                    b.Navigation("Insignias");

                    b.Navigation("MechanicalEquipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.InsigniaSeries", b =>
                {
                    b.Navigation("Insignias");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.InsigniaType", b =>
                {
                    b.Navigation("Insignias");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.LiteratureSeries", b =>
                {
                    b.Navigation("Literatures");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.LiteratureType", b =>
                {
                    b.Navigation("Literatures");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Manufacturer", b =>
                {
                    b.Navigation("MechanicalEquipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Material", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Insignias");

                    b.Navigation("MechanicalEquipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.MechanicalEquipmentType", b =>
                {
                    b.Navigation("MechanicalEquipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Origin", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Equipments");

                    b.Navigation("Insignias");

                    b.Navigation("MechanicalEquipments");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.Publisher", b =>
                {
                    b.Navigation("Literatures");
                });

            modelBuilder.Entity("MilitaryCollectiblesBackend.Models.StorageArea", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Equipments");

                    b.Navigation("Insignias");

                    b.Navigation("Literatures");

                    b.Navigation("MechanicalEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
